### ISSUE TITLE
Mainnet interruption - June 10th (block 1920929)

### ISSUE THREAD

**Issue by SteveHenley** [rchain-community/mainnet-outage#32]
| Questions       |        Needed Information     |
| ------------- |:----------------------------------------------:|
| Date                  |             June 12th, 2023                            |
| Outage Type           |       Interruption                                 |
| Nature of Problem     |       Unknown hardware fault in a "spare" Hetzner server.                              |
| Time Circuit Went Down     |         DD:June 12    HH: 4:00 UTC   MM:  12                               |
| Time Circuit Was Restored |         DD:  June 12  HH:  4:00  MM:  13                               |
| Site                  |        Germany                                |
| Operator              |                   Hetzner                     |
| Current Status        |             up                           |
| Action Taken          |               system self corrected                         |

**Comment by SteveHenley** [comment]
Updated AAR with times

**Comment by jetman2** [comment]
@Bill-Kunj what was the nature of this problem?

**Comment by Bill-Kunj** [comment]
There is an unknown hardware fault in one of our "spare" Hetzner servers (internal `10.4.1.102`, external `168.119.90.150`) -- it occasionally just goes down. Server hardware diagnosis is impossible since we have no physical access
This does not affect the availability of the network, since it is a "spare" server and the management network self-corrects. However, a fault in a spare reduces our availability.
This is not unexpected, but is important. L3 plans to eliminate this faulty server during our June server consolidation.

In the meantime, this fault may pop up again.
@jetman2 It would be helpful if L1 could produce a prometheus/grafana alert that detects this outage so L2/L3 can respond rapidly.

**Comment by Bill-Kunj** [comment]
This failure has occurred again today. Server has been rebooted with no affect on the running mainnet.
This was reported in the `mainnet-alert` channel
https://discord.com/channels/1068875609935204464/1094603282107867196/1121930815773880331

**Comment by DPMBarnes** [comment]
Main Net is no longer in use.
